/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 // #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{


	// Encendemos la señal de reloj para poder usar el GPIOA - se hace con el RCC  AHB1

	//RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;  //Escribimos un 1 para encenderlo, ponemos una mascara RCC_AHB1ENR_GPIOAEN, la encontramos en el stm32f411xe.h

	//GPIOA->MODER |= GPIO_MODER_MODE0_1;  //NOMBRE DEL PERISFERICO_NOMBRE DEL REGISTRO QUE QUEREMOS MODIFICAR_NOMBRE DEL REGISTRO QUE QUEREMOS MODIFICAR


	/*------------------LED BLINKI--------------*/

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	/* Configuracion del pin A5 como salida*/
	GPIOA->MODER |= (0b01 << GPIO_MODER_MODE5_Pos);

	/*configuracion del pin A5 como slaida push-pull*/
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT5);

	/*Limpiando la posicion de los bits que deseo borrar*/
	GPIOA->OSPEEDR &= ~(0B11 << GPIO_OSPEEDR_OSPEED5_Pos);

	/*Seleccionando la velocidad fast*/
	GPIOA->OSPEEDR |= (0B10 << GPIO_OSPEEDR_OSPEED5_Pos);

	GPIOA->ODR |= (GPIO_ODR_OD5);

	/* Loop forever */
	while (1){

	}
	return 0;
}



